
all:
	pdflatex -output-directory ../../fig/t1/ t1/SAU_scheme.tex
	pdflatex -output-directory ../../fig/t1/ t1/SAU_structure.tex
	pdflatex -output-directory ../../fig/t1/ t1/feedback.tex
	pdflatex -output-directory ../../fig/t1/ t1/feedback_pendulum.tex
	pdflatex -output-directory ../../fig/t1/ t1/program.tex
	pdflatex -output-directory ../../fig/t2/ t2/*.tex